Repository factcast/factcast, pull requests merged in 2021-07, with the labels that each got.

#1404 #1104 Use Transformer (pgsql) for schema-registry cli
  factcast-schema-registry-cli/pom.xml
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/config/TransformerConfig.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/js/JsFunctionExecutor.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/js/JsFunctionExecutorImpl.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/utils/SchemaServiceImpl.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluator.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/ValidationServiceImpl.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/ProjectStructureValidationServiceImpl.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImpl.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/ValidTransformationFolderValidator.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteListFilterService.kt
  factcast-schema-registry-cli/src/test/kotlin/io/kotlintest/provided/ProjectConfig.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/commands/CommandServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/fs/FileSystemServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/js/JsFunctionNashornExecutorTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/project/ProjectServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/project/structure/EventFolderKtTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/project/structure/EventVersionFolderTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/project/structure/NamespaceFolderTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/project/structure/ProjectFolderTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/project/structure/TransformationFolderTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/registry/impl/DistributionCreatorServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/registry/impl/FactcastIndexCreatorImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/registry/impl/HugoTemplateServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/registry/impl/IndexFileCalculatorImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/utils/ChecksumServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/utils/FilterTitleFromJsonTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/utils/SchemaServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/MissingTransformationCalculatorImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorIntTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/ValidationServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/ExampleValidationServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/ProjectStructureValidationServiceIntTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/ValidTransformationFolderValidatorTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/ValidVersionFolderValidatorTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteListFilterServiceImplTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteListTest.kt
  factcast-schema-registry-cli/src/test/resources/fixtures/transformation/event.json
  factcast-schema-registry-cli/src/test/resources/fixtures/transformation/failing.js
  factcast-schema-registry-cli/src/test/resources/fixtures/transformation/working.js
  pom.xml
Labels: robustness

#1445 #1444: remove obsolete index
  factcast-store-pgsql/src/main/resources/db/changelog/db.changelog-master.yaml
  factcast-store-pgsql/src/main/resources/db/changelog/factcast/issue1444/obsolete_index.sql
Labels: polish

#1449 #1447: reduce number of queries triggered by publication
  build.trigger
  factcast-client-grpc/src/test/java/org/factcast/client/grpc/GrpcFactStoreTest.java
  factcast-core/src/main/java/org/factcast/core/DefaultFactCast.java
  factcast-core/src/main/java/org/factcast/core/snap/SnapshotId.java
  factcast-factus/src/main/java/org/factcast/factus/snapshot/AggregateSnapshotRepositoryImpl.java
  factcast-factus/src/main/java/org/factcast/factus/snapshot/ProjectionSnapshotRepositoryImpl.java
  factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
  factcast-factus/src/test/java/org/factcast/factus/snapshot/AggregateSnapshotRepositoryImplTest.java
  factcast-grpc-api/src/main/java/org/factcast/grpc/api/conv/ProtoConverter.java
  factcast-grpc-api/src/test/java/org/factcast/grpc/api/conv/ProtoConverterTest.java
  factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/SnapshotCacheTest.java
  factcast-server-grpc/src/test/java/org/factcast/server/grpc/FactStoreGrpcServiceTest.java
  factcast-snapshotcache-redisson/src/test/java/org/factcast/core/snap/redisson/RedissonSnapshotCacheTest.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/CondensedQueryExecutor.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgConstants.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStream.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgListener.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/snapcache/PgSnapshotCacheCompactor.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/TransformationCacheCompactor.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/CondensedQueryExecutorTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgFactStoreTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/listen/PgListenerTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/snapcache/SnapshotCacheTest.java
  factcast-store-pgsql/src/test/resources/simplelogger.properties
Labels: scalability

#1455 WIP: #1421: applevel keepalive
  .githooks/pre-commit.d/spotless
  factcast-client-grpc/src/main/java/org/factcast/client/grpc/ClientStreamObserver.java
  factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
  factcast-client-grpc/src/test/java/org/factcast/client/grpc/ClientStreamObserverTest.java
  factcast-core/src/main/java/org/factcast/core/subscription/FluentSubscriptionRequest.java
  factcast-core/src/main/java/org/factcast/core/subscription/MissingTransformationInformationException.java
  factcast-core/src/main/java/org/factcast/core/subscription/ReconnectingFactSubscriptionWrapper.java
  factcast-core/src/main/java/org/factcast/core/subscription/SpecBuilder.java
  factcast-core/src/main/java/org/factcast/core/subscription/StaleSubscriptionDetectedException.java
  factcast-core/src/main/java/org/factcast/core/subscription/SubscriptionRequest.java
  factcast-core/src/main/java/org/factcast/core/subscription/SubscriptionRequestTO.java
  factcast-core/src/test/java/org/factcast/core/subscription/FluentSubscriptionRequestTest.java
  factcast-core/src/test/java/org/factcast/core/subscription/ReconnectingFactSubscriptionWrapperTest.java
  factcast-core/src/test/java/org/factcast/core/subscription/SubscriptionRequestTOTest.java
  factcast-grpc-api/src/main/java/org/factcast/grpc/api/conv/ProtoConverter.java
  factcast-grpc-api/src/main/proto/FactStore.proto
  factcast-grpc-api/src/test/java/org/factcast/grpc/api/conv/ProtoConverterTest.java
  factcast-itests/factcast-itests-exception-handling/src/main/resources/application.properties
  factcast-itests/factcast-itests-exception-handling/src/test/java/org/factcast/itests/exception/handling/TransportLayerExceptionHandling.java
  factcast-itests/factcast-itests-transformation/src/test/java/org/factcast/itests/transformation/TransformationTest.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcObserverAdapter.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/OnCancelHandler.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/TransportLayerException.java
  factcast-server-grpc/src/test/java/org/factcast/server/grpc/GrpcObserverAdapterTest.java
  factcast-server-grpc/src/test/java/org/factcast/server/grpc/OnCancelHandlerTest.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStream.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/fetching/PgFetchingCatchup.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/tmppaged/PgTmpPagedCatchup.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/chains/TransformationChains.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/TransformationChainsTest.java
Labels: robustness

#1468 #1462: Introduce GraalJs based ScriptEngine
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/config/TransformerConfig.kt
  factcast-store-pgsql/pom.xml
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/TransformationConfiguration.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/chains/GraalJsTransformer.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/GraalJsTransformerTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/NashornTransformerTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/TransformationChainsTest.java
  pom.xml
Labels: enhancement

#1469 #1401: removed executeUpdate
  factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
  factcast-factus/src/main/java/org/factcast/factus/projection/Projection.java
  factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
  factcast-itests/factcast-itests-factus/src/main/resources/application.properties
Labels: API, polish

#1466 #1454: added routine check for index validity
  factcast-site/documentation/content/setup/properties.md
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgConstants.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/check/IndexCheck.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/check/IndexCheckTest.java
Labels: robustness

#1465 #1464: rename StateAware -> FactStreamPositionAware
  build.trigger
  factcast-factus-redis/src/main/java/org/factcast/factus/redis/AbstractRedisProjection.java
  factcast-factus-redis/src/test/java/org/factcast/factus/redis/AbstractRedisManagedProjectionTest.java
  factcast-factus-redis/src/test/java/org/factcast/factus/redis/batch/RedisBatchedLensTest.java
  factcast-factus-redis/src/test/java/org/factcast/factus/redis/tx/RedisTransactionalLensTest.java
  factcast-factus-spring-tx/src/main/java/org/factcast/factus/spring/tx/AbstractSpringTxProjection.java
  factcast-factus-spring-tx/src/test/java/org/factcast/factus/spring/tx/ASpringTxManagedProjection.java
  factcast-factus-spring-tx/src/test/java/org/factcast/factus/spring/tx/ASpringTxSubscribedProjection.java
  factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
  factcast-factus/src/main/java/org/factcast/factus/projection/FactStreamPositionAware.java
  factcast-factus/src/main/java/org/factcast/factus/projection/LocalFactStreamPosition.java
  factcast-factus/src/main/java/org/factcast/factus/projection/LocalManagedProjection.java
  factcast-factus/src/main/java/org/factcast/factus/projection/LocalSubscribedProjection.java
  factcast-factus/src/main/java/org/factcast/factus/projection/ManagedProjection.java
  factcast-factus/src/main/java/org/factcast/factus/projection/SubscribedProjection.java
  factcast-factus/src/main/java/org/factcast/factus/projector/ProjectorImpl.java
  factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
  factcast-factus/src/test/java/org/factcast/factus/projector/ProjectorImplTest.java
  factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/FactusClientTest.java
  factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/RedisBatchingITest.java
  factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/RedisTransactionalITest.java
  factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/SpringTransactionalITest.java
Labels: polish
