Repository factcast/factcast, pull requests merged in 2021-06, with the labels that each got.

#1343 Issue1340 ignore conflicting transformation results
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/cache/PgTransformationCache.java
Labels: easy

#1344 Issue1342: Use redis native TTL in RedisSnapshotCache
  factcast-snapshotcache-redisson/src/main/java/org/factcast/core/snap/redisson/RedissonSnapshotCache.java
  factcast-snapshotcache-redisson/src/test/java/org/factcast/core/snap/redisson/RedissonSnapshotCacheTest.java
Labels: polish

#1375 Issue1368 Cache serial lookup by id
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStoreInternalConfiguration.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/StoreMetrics.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/query/PgFactIdToSerialMapper.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgFactIdToSerMapperTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/query/PgFactIdToSerialMapperTest.java
Labels: easy

#1392 Reset tx/batch to null in order to allow client to retry
  factcast-factus-redis/src/main/java/org/factcast/factus/redis/batch/RedissonBatchManager.java
  factcast-factus-redis/src/main/java/org/factcast/factus/redis/tx/RedissonTxManager.java
  factcast-factus-redis/src/test/java/org/factcast/factus/redis/batch/RedissonBatchManagerTest.java
  factcast-factus-redis/src/test/java/org/factcast/factus/redis/tx/RedissonTxManagerTest.java
  factcast-factus-spring-tx/src/main/java/org/factcast/factus/spring/tx/SpringTxManager.java
  factcast-factus-spring-tx/src/test/java/org/factcast/factus/spring/tx/SpringTxManagerTest.java
Labels: robustness
