Repository factcast/factcast, pull requests merged in 2021-09, with the labels that each got.

#1559 #1553-condense-notifications: Grouping channel notifications
  factcast-store/src/main/java/org/factcast/store/internal/CondensedQueryExecutor.java
  factcast-store/src/main/java/org/factcast/store/internal/listen/PgListener.java
  factcast-store/src/main/java/org/factcast/store/internal/listen/SignalDeduplicationSet.java
  factcast-store/src/main/resources/db/changelog/db.changelog-master.yaml
  factcast-store/src/main/resources/db/changelog/factcast/issue1553/updateNotifyFactInsert.sql
  factcast-store/src/test/java/org/factcast/store/internal/listen/PgListenerTest.java
  factcast-store/src/test/java/org/factcast/store/internal/listen/SignalDeduplicationSetTest.java
Labels: performance

#1571 Issue1568 socket waittime and exception handling
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/BlockingStreamObserver.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcObserverAdapter.java
  factcast-server-grpc/src/test/java/org/factcast/server/grpc/BlockingStreamObserverTest.java
  factcast-store/src/main/java/org/factcast/store/internal/PgSubscriptionFactory.java
Labels: robustness

#1573 issue1572 version logging on startup
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
Labels: observability
