Repository factcast/factcast, pull requests merged in 2022-03, with the labels that each got.

#1843 #1842: fix concurrency issues with Graaljs
  factcast-store/src/main/java/org/factcast/store/registry/transformation/chains/GraalJsTransformer.java
  factcast-store/src/test/java/org/factcast/store/registry/transformation/chains/GraalJsTransformerTest.java
Labels: bug

#1846 #1842: added comment
  factcast-store/src/main/java/org/factcast/store/registry/transformation/chains/GraalJsTransformer.java
Labels: documentation

#1850 Add possibility for skipping transformations check during schema-reg cli validation
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluator.kt
  factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImpl.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorIntTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorTest.kt
  factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImplTest.kt
  factcast-schema-registry-cli/src/test/resources/fixtures/transformation/skipped.js
Labels: enhancement, scripting

#1852 #1851: do not get from closed rs to set serial
  factcast-store/src/main/java/org/factcast/store/internal/PgFactStream.java
  factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTest.java
Labels: bug

#1874 Issue1816
  factcast-site/documentation-docsy/content/en/Usage/factus/tips.md
Labels: documentation
